-- ==============================================================================
-- CSL ERP — Request Documents Table
-- Menyimpan metadata dokumen GDrive yang di-share CSL ke requester
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.csl_request_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES public.csl_requests(id) ON DELETE CASCADE,
    
    -- Metadata dokumen
    doc_name VARCHAR(255) NOT NULL,          -- Nama dokumen, misal: "Surat Kuasa Final"
    doc_type VARCHAR(100),                   -- Jenis, misal: "Surat Kuasa", "Draft Perjanjian"
    gdrive_url TEXT NOT NULL,               -- Link Google Drive (private, dibagikan ke requester)
    gdrive_file_id VARCHAR(255),            -- File ID dari GDrive (opsional)
    
    -- Siapa yang upload
    uploaded_by_name VARCHAR(255) NOT NULL,
    uploaded_by_id TEXT,
    
    -- Akses
    is_visible_to_requester BOOLEAN DEFAULT TRUE,  -- Bisa disembunyikan sementara
    
    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Index
CREATE INDEX IF NOT EXISTS idx_csl_req_docs_request_id ON public.csl_request_documents(request_id);

-- Enable RLS
ALTER TABLE public.csl_request_documents ENABLE ROW LEVEL SECURITY;

-- Policy: CSL team bisa baca semua, requester hanya bisa baca dokumen request miliknya
DROP POLICY IF EXISTS "CSL team can manage documents" ON public.csl_request_documents;
CREATE POLICY "CSL team can manage documents" ON public.csl_request_documents
    FOR ALL TO authenticated, anon
    USING (
        auth.email() IS NULL
        OR public.is_csl_team()
    )
    WITH CHECK (
        auth.email() IS NULL
        OR public.is_csl_team()
    );

-- Requester bisa lihat dokumen milik request mereka (READ ONLY)
DROP POLICY IF EXISTS "Requester can view their request documents" ON public.csl_request_documents;
CREATE POLICY "Requester can view their request documents" ON public.csl_request_documents
    FOR SELECT TO authenticated, anon
    USING (
        auth.email() IS NULL
        OR public.is_csl_team()
        OR (
            is_visible_to_requester = TRUE
            AND EXISTS (
                SELECT 1 FROM public.csl_requests r
                WHERE r.id = request_id
                AND r.requester_email = auth.email()
            )
        )
    );

-- Grant
GRANT SELECT, INSERT, UPDATE, DELETE ON public.csl_request_documents TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.csl_request_documents_id_seq TO anon, authenticated, service_role;
