-- Migration for CSL Request Logs
-- Drop and recreate to fix actor_id type mismatch (UUID → TEXT)
DROP TABLE IF EXISTS public.csl_request_logs CASCADE;

CREATE TABLE IF NOT EXISTS public.csl_request_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT REFERENCES public.csl_requests(id) ON DELETE CASCADE,
    status VARCHAR(50) NOT NULL,
    actor_name VARCHAR(255) NOT NULL,
    actor_id TEXT,                    -- TEXT agar kompatibel dengan semua format user ID
    note TEXT,
    has_files BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Enable RLS
ALTER TABLE public.csl_request_logs ENABLE ROW LEVEL SECURITY;

-- Policies: semua user bisa lihat dan tambah log
DROP POLICY IF EXISTS "Enable read access for all users" ON public.csl_request_logs;
CREATE POLICY "Enable read access for all users" ON public.csl_request_logs
    FOR SELECT TO authenticated, anon USING (true);

DROP POLICY IF EXISTS "Enable insert for all users" ON public.csl_request_logs;
CREATE POLICY "Enable insert for all users" ON public.csl_request_logs
    FOR INSERT TO authenticated, anon WITH CHECK (true);

-- Grant privileges
GRANT SELECT, INSERT ON public.csl_request_logs TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.csl_request_logs_id_seq TO anon, authenticated, service_role;

-- Index for faster queries
CREATE INDEX IF NOT EXISTS idx_csl_request_logs_request_id ON public.csl_request_logs(request_id);
