-- ==============================================================================
-- CSL ERP — Phase 3: Routine Activity
-- Creates tables for managing recurring routine tasks and their instances
-- ==============================================================================

-- 1. Routine Master Table
CREATE TABLE IF NOT EXISTS public.csl_routines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    category VARCHAR(100) NOT NULL, -- e.g., 'Compliance', 'Tax', 'Permit Renewal'
    frequency VARCHAR(50) NOT NULL CHECK (frequency IN ('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'SEMI_ANNUALLY', 'ANNUALLY')),
    due_day INTEGER, -- e.g., Day of the month (1-31), or day of the year for annual
    assigned_pic_id TEXT, -- If null, falls to general CSL Team pool
    assigned_pic_name VARCHAR(255),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Routine Instances Table (The actual tasks to be done per period)
CREATE TABLE IF NOT EXISTS public.csl_routine_instances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routine_id BIGINT REFERENCES public.csl_routines(id) ON DELETE CASCADE,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    due_date DATE NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE', 'CANCELLED')),
    completion_notes TEXT,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Indexes for performance
CREATE INDEX IF NOT EXISTS idx_csl_routines_category ON public.csl_routines(category);
CREATE INDEX IF NOT EXISTS idx_csl_routine_instances_routine ON public.csl_routine_instances(routine_id);
CREATE INDEX IF NOT EXISTS idx_csl_routine_instances_status ON public.csl_routine_instances(status);
CREATE INDEX IF NOT EXISTS idx_csl_routine_instances_due_date ON public.csl_routine_instances(due_date);

-- 4. Enable Row Level Security
ALTER TABLE public.csl_routines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.csl_routine_instances ENABLE ROW LEVEL SECURITY;

-- 5. Security Policies
-- Everyone can view routines (or maybe just CSL Team, but for now we'll allow all authenticated to view)
DROP POLICY IF EXISTS "Allow select routines for authenticated users" ON public.csl_routines;
CREATE POLICY "Allow select routines for authenticated users" ON public.csl_routines
    FOR SELECT TO authenticated, anon USING (true);

-- Only CSL Team can manage (insert/update/delete) routines
DROP POLICY IF EXISTS "Allow manage routines for CSL team" ON public.csl_routines;
CREATE POLICY "Allow manage routines for CSL team" ON public.csl_routines
    FOR ALL TO authenticated, anon USING (auth.email() IS NULL OR public.is_csl_team());

-- Instances Policies (View)
DROP POLICY IF EXISTS "Allow select instances for authenticated users" ON public.csl_routine_instances;
CREATE POLICY "Allow select instances for authenticated users" ON public.csl_routine_instances
    FOR SELECT TO authenticated, anon USING (true);

-- Instances Policies (Manage)
DROP POLICY IF EXISTS "Allow manage instances for CSL team" ON public.csl_routine_instances;
CREATE POLICY "Allow manage instances for CSL team" ON public.csl_routine_instances
    FOR ALL TO authenticated, anon USING (auth.email() IS NULL OR public.is_csl_team());

-- Grant Privileges
GRANT SELECT, INSERT, UPDATE, DELETE ON public.csl_routines TO anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.csl_routine_instances TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.csl_routines_id_seq TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.csl_routine_instances_id_seq TO anon, authenticated, service_role;
