-- ==============================================================================
-- CSL ERP — Phone Directory Table
-- Creates table for managing legal contacts, lawyers, vendors, & government agencies
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.csl_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(50) NOT NULL CHECK (category IN ('Lawyer', 'Vendor', 'Government', 'Other')),
    organization VARCHAR(255),
    phone VARCHAR(100) NOT NULL,
    email VARCHAR(255),
    city VARCHAR(100) DEFAULT 'Jakarta',
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS & Security
ALTER TABLE public.csl_contacts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow select contacts for authenticated" ON public.csl_contacts;
CREATE POLICY "Allow select contacts for authenticated" ON public.csl_contacts
    FOR SELECT TO authenticated, anon USING (true);

DROP POLICY IF EXISTS "Allow manage contacts for authenticated" ON public.csl_contacts;
CREATE POLICY "Allow manage contacts for authenticated" ON public.csl_contacts
    FOR ALL TO authenticated, anon USING (true);

-- Grant Privileges
GRANT SELECT, INSERT, UPDATE, DELETE ON public.csl_contacts TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.csl_contacts_id_seq TO anon, authenticated, service_role;
