-- Migration: CSL Phase 1 — Request/Ticketing & SLA System
-- Creates csl_request_categories, csl_company_holidays, csl_requests, and csl_request_activities

-- 1. Create Request Categories Table
CREATE TABLE IF NOT EXISTS public.csl_request_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    sla_days INTEGER NOT NULL DEFAULT 5,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Company Holidays Table
CREATE TABLE IF NOT EXISTS public.csl_company_holidays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holiday_date DATE UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create CSL Requests Table
CREATE TABLE IF NOT EXISTS public.csl_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_number VARCHAR(100) UNIQUE NOT NULL,
    category_id BIGINT REFERENCES public.csl_request_categories(id) ON DELETE RESTRICT,
    requester_id TEXT,
    requester_email VARCHAR(255) NOT NULL,
    requester_name VARCHAR(255) NOT NULL,
    department VARCHAR(255) NOT NULL,
    company VARCHAR(255) NOT NULL,
    assigned_pic_id TEXT,
    assigned_pic_name VARCHAR(255),
    priority VARCHAR(50) NOT NULL CHECK (priority IN ('Low', 'Medium', 'High', 'Critical')),
    status VARCHAR(50) NOT NULL DEFAULT 'DRAFT' CHECK (status IN (
        'DRAFT', 'SUBMITTED', 'ACKNOWLEDGED', 'IN_REVIEW', 'REVISION_REQUIRED', 
        'PROCESSING', 'COMPLETED', 'RESPONDED', 'CLOSED', 'REJECTED', 'CANCELLED'
    )),
    description TEXT NOT NULL,
    progress INTEGER NOT NULL DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
    required_date DATE,
    sla_target_days INTEGER NOT NULL,
    sla_due_date TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create Request Activities Table
CREATE TABLE IF NOT EXISTS public.csl_request_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT REFERENCES public.csl_requests(id) ON DELETE CASCADE,
    actor_name VARCHAR(255) NOT NULL,
    actor_email VARCHAR(255) NOT NULL,
    action TEXT NOT NULL,
    from_status VARCHAR(50),
    to_status VARCHAR(50),
    details TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Indexes for optimization
CREATE INDEX IF NOT EXISTS idx_csl_requests_status ON public.csl_requests(status);
CREATE INDEX IF NOT EXISTS idx_csl_requests_requester ON public.csl_requests(requester_email);
CREATE INDEX IF NOT EXISTS idx_csl_requests_pic ON public.csl_requests(assigned_pic_id);
CREATE INDEX IF NOT EXISTS idx_csl_request_activities_req ON public.csl_request_activities(request_id);

-- 5. Seed Request Categories
INSERT INTO public.csl_request_categories (code, name, sla_days, description) VALUES
('AGR', 'Agreement', 5, 'Contract drafting, revision, and review requests'),
('LREV', 'Legal Review', 5, 'Review of external templates, letters, and business documents'),
('CORPSECR', 'Corporate Secretary', 5, 'Board minutes, circular resolutions, and statutory filings'),
('OSS', 'OSS', 14, 'OSS system permits and licensing registration actions'),
('LIC', 'Licensing', 10, 'General regional and sector-specific operational licenses'),
('NOTARY', 'Notary', 7, 'Deed preparation, legalization, and notarization coordination'),
('LEGALOP', 'Legal Opinion', 5, 'Formal written legal analysis and advisory opinions'),
('DOCREQ', 'Document Request', 2, 'Retrieval of corporate constitutional documents or active permits'),
('COMPLIANCE', 'Compliance', 5, 'Periodic regulatory reports and business compliance reviews'),
('OTHER', 'Other', 5, 'General and miscellaneous secretarial or legal support')
ON CONFLICT (code) DO UPDATE SET 
    name = EXCLUDED.name,
    sla_days = EXCLUDED.sla_days,
    description = EXCLUDED.description;

-- 6. Seed Indonesian National Holidays for 2026
INSERT INTO public.csl_company_holidays (holiday_date, name) VALUES
('2026-01-01', 'New Year''s Day'),
('2026-02-15', 'Isra Mi''raj'),
('2026-02-17', 'Chinese New Year'),
('2026-03-19', 'Nyepi (Balinese Saka New Year)'),
('2026-04-03', 'Good Friday'),
('2026-04-18', 'Hari Raya Idul Fitri 1447 H'),
('2026-04-19', 'Hari Raya Idul Fitri Holiday'),
('2026-04-20', 'Hari Raya Idul Fitri Holiday'),
('2026-05-01', 'International Labor Day'),
('2026-05-13', 'Waisak Day'),
('2026-05-14', 'Ascension Day of Jesus Christ'),
('2026-06-01', 'Pancasila Day'),
('2026-06-27', 'Hari Raya Idul Adha 1447 H'),
('2026-07-16', 'Islamic New Year 1448 H'),
('2026-08-17', 'Independence Day of Indonesia'),
('2026-09-24', 'Maulid Nabi Muhammad SAW'),
('2026-12-25', 'Christmas Day')
ON CONFLICT (holiday_date) DO NOTHING;

-- 7. Define Security Helper Function
CREATE OR REPLACE FUNCTION public.is_csl_team()
RETURNS BOOLEAN AS $$
DECLARE
  u_role TEXT;
  u_groups TEXT[];
BEGIN
  -- Fetch role and groups for auth user email
  SELECT role, groups INTO u_role, u_groups 
  FROM public.user_accounts 
  WHERE email = auth.email() LIMIT 1;
  
  IF u_role IS NULL THEN
    RETURN FALSE;
  END IF;
  
  -- Return true if user has admin/staff role or belongs to CSL/Admin/IT groups
  IF u_role ILIKE '%admin%' 
     OR u_role ILIKE '%staff%' 
     OR u_role = 'CSL_ADMIN' 
     OR u_role = 'CSL_STAFF' 
     OR 'admin' = ANY(u_groups) 
     OR 'csl_admin' = ANY(u_groups) 
     OR 'csl_staff' = ANY(u_groups) 
     OR 'it' = ANY(u_groups) THEN
    RETURN TRUE;
  END IF;
  
  RETURN FALSE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 8. Enable Row Level Security (RLS) and Create Policies
ALTER TABLE public.csl_request_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.csl_company_holidays ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.csl_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.csl_request_activities ENABLE ROW LEVEL SECURITY;

-- Request Categories Policies
DROP POLICY IF EXISTS "Allow select for all authenticated users" ON public.csl_request_categories;
CREATE POLICY "Allow select for all authenticated users" ON public.csl_request_categories
    FOR SELECT TO authenticated, anon USING (true);

DROP POLICY IF EXISTS "Allow write for CSL admins" ON public.csl_request_categories;
CREATE POLICY "Allow write for CSL admins" ON public.csl_request_categories
    FOR ALL TO authenticated, anon USING (auth.email() IS NULL OR public.is_csl_team());

-- Company Holidays Policies
DROP POLICY IF EXISTS "Allow select holidays for all" ON public.csl_company_holidays;
CREATE POLICY "Allow select holidays for all" ON public.csl_company_holidays
    FOR SELECT TO authenticated, anon USING (true);

DROP POLICY IF EXISTS "Allow manage holidays for CSL admins" ON public.csl_company_holidays;
CREATE POLICY "Allow manage holidays for CSL admins" ON public.csl_company_holidays
    FOR ALL TO authenticated, anon USING (auth.email() IS NULL OR public.is_csl_team());

-- Requests Policies
DROP POLICY IF EXISTS "Allow requests access based on role" ON public.csl_requests;
CREATE POLICY "Allow requests access based on role" ON public.csl_requests
    FOR ALL TO authenticated, anon 
    USING (auth.email() IS NULL OR public.is_csl_team() OR requester_email = auth.email())
    WITH CHECK (auth.email() IS NULL OR public.is_csl_team() OR requester_email = auth.email());

-- Request Activities Policies
DROP POLICY IF EXISTS "Allow activities access based on role" ON public.csl_request_activities;
CREATE POLICY "Allow activities access based on role" ON public.csl_request_activities
    FOR ALL TO authenticated, anon 
    USING (auth.email() IS NULL OR public.is_csl_team() OR EXISTS (
        SELECT 1 FROM public.csl_requests r 
        WHERE r.id = request_id AND r.requester_email = auth.email()
    ))
    WITH CHECK (auth.email() IS NULL OR public.is_csl_team() OR EXISTS (
        SELECT 1 FROM public.csl_requests r 
        WHERE r.id = request_id AND r.requester_email = auth.email()
    ));
