-- ============================================================
-- JALANKAN INI DI: Supabase Dashboard → SQL Editor → Run
-- Tujuan: Membuat tabel companies untuk menu Settings
-- ============================================================

CREATE TABLE IF NOT EXISTS public.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(50) UNIQUE NOT NULL,
    departments INTEGER DEFAULT 0,
    employees INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any
DROP POLICY IF EXISTS "Allow authenticated read all companies" ON public.companies;
DROP POLICY IF EXISTS "Allow csl_team to insert companies" ON public.companies;
DROP POLICY IF EXISTS "Allow csl_team to update companies" ON public.companies;
DROP POLICY IF EXISTS "Allow csl_admin to delete companies" ON public.companies;

-- 1. Allow any authenticated user to read all companies
CREATE POLICY "Allow authenticated read all companies"
ON public.companies FOR SELECT TO authenticated USING (true);

-- 2. Allow CSL team to manage companies
CREATE POLICY "Allow csl_team to insert companies"
ON public.companies FOR INSERT TO authenticated WITH CHECK (public.is_csl_team());

CREATE POLICY "Allow csl_team to update companies"
ON public.companies FOR UPDATE TO authenticated USING (public.is_csl_team());

CREATE POLICY "Allow csl_admin to delete companies"
ON public.companies FOR DELETE TO authenticated USING (public.is_csl_team());

-- Insert default seed data
INSERT INTO public.companies (name, code, departments, employees) VALUES
('PT GESIT', 'GESIT', 12, 156),
('PT Mitra Sejati', 'MITRA', 5, 48),
('PT Teknologi Maju', 'TEKMA', 3, 22)
ON CONFLICT (code) DO NOTHING;
