-- ==============================================================================
-- CSL ERP — Documents Repository Table
-- Dedicated storage for CSL Corporate Documents & Agreements in Google Drive
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.csl_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_number VARCHAR(100),
    title VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL DEFAULT 'Agreement', -- 'Agreement', 'Legal Document', 'Permit', 'Google Drive', 'General'
    counterparty VARCHAR(255) DEFAULT '-',
    contract_value VARCHAR(100) DEFAULT '-',
    effective_date DATE,
    expired_date DATE,
    status VARCHAR(50) DEFAULT 'ACTIVE', -- 'ACTIVE', 'EXPIRING_SOON', 'EXPIRED', 'ARCHIVED'
    auto_renew BOOLEAN DEFAULT FALSE,
    issuer VARCHAR(255) DEFAULT '-',
    file_name VARCHAR(255),
    gdrive_url TEXT,
    gdrive_file_id VARCHAR(255),
    folder_type VARCHAR(50) DEFAULT 'CSL_DOCUMENTS',
    uploaded_by VARCHAR(255),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Index
CREATE INDEX IF NOT EXISTS idx_csl_documents_category ON public.csl_documents(category);

-- RLS
ALTER TABLE public.csl_documents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public access for csl_documents" ON public.csl_documents;
CREATE POLICY "Public access for csl_documents" ON public.csl_documents
    FOR ALL TO authenticated, anon USING (true) WITH CHECK (true);

-- Permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON public.csl_documents TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.csl_documents_id_seq TO anon, authenticated, service_role;

-- Initial Seed Data
INSERT INTO public.csl_documents (doc_number, title, category, counterparty, contract_value, effective_date, expired_date, status, auto_renew, issuer, notes, folder_type)
VALUES
('AGR/2026/001', 'Master Services Agreement - PT Tekno Utama', 'Agreement', 'PT Tekno Utama', 'Rp 450.000.000', '2026-01-15', '2027-01-15', 'ACTIVE', true, '-', 'Perjanjian Jasa Layanan IT & Cloud Support', 'CSL_DOCUMENTS'),
('AGR/2026/004', 'Non-Disclosure Agreement (NDA) - CV Mitra Digital', 'Agreement', 'CV Mitra Digital', '-', '2026-02-01', '2028-02-01', 'ACTIVE', false, '-', 'Kerahasiaan data dan source code', 'CSL_DOCUMENTS'),
('LEG/2025/089', 'Akta Pendirian & Perubahan Anggaran Dasar PT GESIT', 'Legal Document', '-', '-', '2018-06-14', NULL, 'ACTIVE', false, 'Notaris Dra. Linda Wijaya / Kemenkumham', 'Akta autentik pendirian perseroan', 'CSL_DOCUMENTS'),
('OSS/2026/012', 'NIB & Izin Usaha Operasional - OSS RBA', 'Permit', '-', '-', '2021-02-10', NULL, 'ACTIVE', false, 'Kementerian Investasi / BKPM', 'Nomor Induk Berusaha & Izin Standar', 'CSL_DOCUMENTS')
ON CONFLICT DO NOTHING;
